### ISSUE TITLE
CASL fails to compile with Typescript 4.3.X

### ISSUE THREAD

**Issue by ArielPrevu3D** [stalniy/casl#531]
**Describe the bug**
CASL is not compatible with Typescript 4.3.x and fails compilation

**To Reproduce**
1. Install `@casl/ability` v5.3.1 and `typescript` v4.3.x
2. `tsc ./`

**Expected behavior**
CASL should not fail compilation when using Typescript 4.3.x

**Current behavior**
Typescript outputs the following:
```
node_modules/@casl/ability/dist/types/matchers/conditions.d.ts:26:5 - error TS2502: 'produce' is referenced directly or indirectly in its own type annotation.

26     produce: MongoQuery<this[0]>;
```
Related file: https://github.com/stalniy/casl/blob/master/packages/casl-ability/src/matchers/conditions.ts#L71

**CASL Version**
`@casl/ability` v5.3.1

**Environment**:
Node v14.16.1
Typescript 4.3.4
@casl/ability 5.3.1

**Comment by stalniy** [comment]
Thanks for the issue. Need some time to investigate it. Will do this in couple days

**Comment by stalniy** [comment]
You know it's strange, I've just installed latest version of CASL (5.4.3) and typescript (4.3.5) and it compiles without any issues

**Comment by stalniy** [comment]
![Screenshot from 2021-08-22 10-39-37](https://user-images.githubusercontent.com/1159966/130346665-739d267a-442d-4b05-bc9f-de32340de557.png)

**Comment by stalniy** [comment]
Close as there is no additional information and it seems that latest compiled well. 

I’ll double check this during making prisma example

**Comment by stalniy** [comment]
Feel free to provide additional details and we I’ll check it

**Comment by ArielPrevu3D** [comment]
Sorry for the waste of time, I misdiagnosed the issue. It had something to do with NestJS compiler options and symlinked dependencies. I still don't really get it, but it compiles with standard `tsc` compiler.

**Comment by stalniy** [comment]
No problem :)

**Comment by sonck201** [comment]
I got the same problem with the same error like @ArielPrevu3D 
```
node 16.4.0
yarn 1.22.11
typescript 4.4.2
@casl/ability 5.4.3
```

**Comment by stalniy** [comment]
Is this nest.js? Can you provide a link to repo with reproducible example, for me to play with it?

**Comment by sonck201** [comment]
@stalniy I have no public repository for sharing with you right now
btw, I'm not using nest.js & mongo

```
express: 4.17.1
sequelize: 6.6.5
mariadb: 2.5.4
```

P/S I could compile fine with `"@casl/ability": "^4.1.6"`. This error has come with `"@casl/ability": "^5.x.x"`

**Comment by stalniy** [comment]
Could you please make a simple repo with basic example that doesn’t work? As I said, in my primitive testing it works, maybe it’s an integration issue with sequelize and TypeORM
