### ISSUE TITLE
Incompatible types for casl v4 and casl/vue

### ISSUE THREAD

**Issue by bodograumann** [stalniy/casl#446]
**Describe the bug**
I was using @casl/vue@0.5.1 and @casl/ability@3.4.0 up to now. Then I decided to upgrade. Of course first going to v4 to handle breaking changes incrementally. This is not possible it seems, because:

`@casl/vue@1.2.1` does not work with `@casl/ability@4.1.6` even though it has `^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.1.0` in its peerDependency specification. The following error occurs, among others:

```
ERROR in /home/bodo/myproject/node_modules/@casl/vue/dist/types/component/can.d.ts(28,135):
28:135 Namespace '"/home/bodo/myproject/node_modules/@casl/ability/dist/types/RuleIndex"' has no exported member 'Public'.
    26 |     passThrough?: boolean;
    27 | };
  > 28 | declare const _default: import("vue/types/vue").ExtendedVue<Vue, {}, {}, {}, AllCanProps<import("@casl/ability/dist/types/RuleIndex").Public<import("@casl/ability").PureAbility<any, any>>>>;
       |                                                                                                                                       ^
    29 | export default _default;
    30 | 
```

**To Reproduce**
1. Setup vue-cli project with @casl/vue and @casl/ability v4.
2. Compile

**Expected behavior**
There should not be a typescript error.

**CASL Version**

`@casl/ability` - v4.1.6
`@casl/vue` - v1.2.1

**Environment**:

`vue-cli` - v4.4.6
`typescript` - v3.9.6
`node.js` - v15.6.0

**Comment by stalniy** [comment]
Well, this is an issue of TypeScript type declarations generator. If you go to the `@casl/vue@1.2.1` tag in git repo, you will see that `Public` is not used there: https://github.com/stalniy/casl/blob/%40casl/vue%401.2.1/packages/casl-vue/src/component/can.ts#L20

**Comment by bodograumann** [comment]
That might well be, but it is still in the `dist` folder that you distribute, is it not?

**Comment by stalniy** [comment]
What I meant is that such kind of bugs are really hard to catch, especially if you use `ts-jest` for running tests (as I do). Trying to produce d.ts with TS 4.x, I saw an issue somewhere in TS repo that describes this kind of bug

**Comment by stalniy** [comment]
TS 4.x produces the same d.ts file. What I can recommend you is to use `@casl/vue@1.1.1` while I'm investigating this issue.

**Comment by bodograumann** [comment]
Thanks that works around the problem or I could go to v5 directly.
In both cases there are some errors in combination with using casl in a component library, that I cannot easily solve. (Something about `Parameters<this["$ability"]["can"]>` type)
So I decided to forgo the update for now.
Need to evaluate whether casl v5 is still viable for our setup, with string subject and pojo subjects not being interoperable anymore. (Was thinking about `Object.assign("User", { ... })` as a workaround though).

**Comment by stalniy** [comment]
string and POJO are interopable in v5. Classes and strings are not

**Comment by stalniy** [comment]
I found workaround for types inconsistency. Will publish new versions in couple of hours

**Comment by stalniy** [comment]
**By the way**, another workaround is to use `skipLibCheck: true` compiler option

**Comment by stalniy** [comment]
I've release @casl/vue@1.2.2 with fixed types for v4. Tested and all good. 

Let me know if you have other upgrade issues. Thanks for reporting it back to me :)
