### ISSUE TITLE
Prisma extension errors with Typescript 4.6.3

### ISSUE THREAD

**Issue by okomarov** [stalniy/casl#613]
**Describe the bug**
Upgrading from Typescript 4.5.5 to 4.6.3 throws this error:

```
node_modules/@casl/prisma/dist/types/prisma/PrismaQuery.d.ts:7:79
error TS2536: Type '"where"' cannot be used to index type 'Exclude<Parameters<ModelDelegates[TModelName]["findFirst"]>[0], null | undefined>'.
```

**To Reproduce**
Install CASL with the prisma extension and run `tsc`.

**Expected behavior**
Compiles without raising Typescript errors.

**CASL Version**
"@casl/ability": "^5.4.3",
"@casl/prisma": "^1.0.1",

**Environment**:
Node 16.14.2
Typescript 4.6.3
yarn 1.22.18
prisma 3.12.0, 3.13.0

**Comment by Loupi** [comment]
Still happens with typecript 4.6.4 too.

**Comment by okomarov** [comment]
> What prisma version do you use? Very likely the issue is in changed prisma types and in typescript. 

Prisma 3.12.0.
Edited original post.

**Comment by Loupi** [comment]
Prisma 3.13.0
Compiles fine with typescript 4.5.5

**Comment by Faithfinder** [comment]
Here's a repro of type errors with Prisma 3.14 (was same with 3.0.2)
https://codesandbox.io/s/cranky-frog-dy6nfq?file=/src/index.ts

No typesafety for conditions with `abilityBuilder` and type error with raw rules.

**Comment by stalniy** [comment]
Guys, I don’t have laptop at the moment. So feel free to submit PRs
